[tool.poetry]
name = "redgyro-blog"
version = "0.1.0"
description = "The RedGyro Blog"
authors = ["Johan Vergeer <johanvergeer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pelican = "^4.2"
markdown = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
