name: Publish site

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Install npm dependencies
      run: cd themes/material-kit && npm i
    - name: Webpack build
      run: cd themes/material-kit && npm run build 
      
